# Generated by Django 4.2.11 on 2025-02-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('dni', models.CharField(max_length=8)),
                ('numero', models.CharField(max_length=9)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
                ('modo', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.mesa')),
            ],
        ),
    ]
