# Generated by Django 4.2.11 on 2025-02-19 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0002_alter_cliente_numero_alter_mesa_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.cliente'),
        ),
    ]
