# Generated by Django 4.2.11 on 2025-02-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0003_alter_mesa_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
