# Generated by Django 4.2.11 on 2025-03-07 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0006_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('hora', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.mesa')),
                ('producto', models.ManyToManyField(to='appKaraoke.producto')),
            ],
        ),
    ]
