# Generated by Django 4.2.11 on 2025-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0008_remove_producto_stock_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='prod'),
        ),
    ]
