# Generated by Django 4.2.11 on 2025-03-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0015_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
