# Generated by Django 4.2.11 on 2025-03-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0016_alter_orden_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='modo',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrdenCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('mesaCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.mesacliente')),
            ],
        ),
        migrations.AddField(
            model_name='mesacliente',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.mesa'),
        ),
    ]
