# Generated by Django 5.1.7 on 2025-03-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0017_mesacliente_remove_cancion_fecha_remove_cancion_mesa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencancion',
            old_name='mesaCliente',
            new_name='mesa_cliente',
        ),
        migrations.AddField(
            model_name='ordencancion',
            name='cancion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.cancion'),
        ),
    ]
