# Generated by Django 5.1.7 on 2025-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0018_rename_mesacliente_ordencancion_mesa_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.CharField(choices=[('1', 'Rock'), ('2', 'Pop'), ('3', 'Salsa'), ('4', 'Balada'), ('5', 'Merenge'), ('6', 'Reggaeton')], max_length=20, null=True),
        ),
    ]
