# Generated by Django 5.1.7 on 2025-03-26 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0020_alter_cancion_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='mesa',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='mesa_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.mesacliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
