# Generated by Django 5.1.7 on 2025-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0025_alter_cancion_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
