# Generated by Django 5.1.7 on 2025-03-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0026_alter_genero_nombre'),
    ]

    operations = [
    ]
