# Generated by Django 5.1.7 on 2025-03-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0028_convertir_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='gen',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
