# Generated by Django 5.1.7 on 2025-03-27 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0029_cancion_gen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='gen',
        ),
        migrations.AddField(
            model_name='cancion',
            name='generos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.genero'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
