# Generated by Django 4.2.11 on 2025-03-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0030_remove_cancion_gen_cancion_generos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='generos',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKaraoke.genero'),
        ),
    ]
