# Generated by Django 4.2.11 on 2025-03-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKaraoke', '0032_alter_genero_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
